use metro_cdmx;

create table
    conductores(
        id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
        name VARCHAR(20) NOT NULL,
        status BOOLEAN NOT NULL DEFAULT false,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id)
    ) DEFAULT CHARSET = UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

create table
    conductores_activos(
        id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
        conductor_id BIGINT(20) UNSIGNED NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        PRIMARY KEY (id),
        CONSTRAINT fk_conductor_id FOREIGN KEY (conductor_id) REFERENCES conductores (id)
    ) DEFAULT CHARSET = UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;