use metro_cdmx;
create table ubicaciones(
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    estacion_id BIGINT(20) UNSIGNED NOT NULL,
    ubicacion point NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_estacion_id FOREIGN KEY (estacion_id) REFERENCES estaciones (id)
) DEFAULT CHARSET = UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;